"""
models/match.py — Pydantic v2 models for entity resolution, scoring, and review.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

from .station import StagingStation


# ═══════════════════════════════════════════════════════════
# ENUMS
# ═══════════════════════════════════════════════════════════

class DecisionType(str, Enum):
    AUTO_MATCH    = "auto_match"
    MANUAL_MATCH  = "manual_match"
    REVIEW_QUEUE  = "review_queue"
    REJECTED      = "rejected"


class BlockingReason(str, Enum):
    GEOHASH    = "geohash"           # Same geohash-6 block (geographic)
    ADMIN      = "admin"             # Same state + municipality (administrative)
    BOTH       = "both"              # Matched by both strategies


class QASeverity(str, Enum):
    HIGH   = "high"
    MEDIUM = "medium"
    LOW    = "low"


# ═══════════════════════════════════════════════════════════
# CANDIDATE PAIR — two staging records to compare
# ═══════════════════════════════════════════════════════════

class CandidatePair(BaseModel):
    """
    A pair of staging records from different sources, generated by the blocking step.
    These are the inputs to the scorer.
    """
    candidate_id: str                        # UUID v4, pipeline-generated
    station_a: StagingStation
    station_b: StagingStation
    blocking_reason: BlockingReason = BlockingReason.GEOHASH

    @property
    def pair_key(self) -> frozenset[str]:
        """Order-invariant key for deduplication."""
        return frozenset([self.station_a.id, self.station_b.id])

    @property
    def sources(self) -> tuple[str, str]:
        return self.station_a.source, self.station_b.source

    model_config = {"arbitrary_types_allowed": True}


# ═══════════════════════════════════════════════════════════
# MATCH SCORES — scoring results for a candidate pair
# ═══════════════════════════════════════════════════════════

class MatchScores(BaseModel):
    """
    Five-dimension match scores for a candidate pair, plus composite.
    All individual scores are in [0.0, 1.0].
    """
    candidate_id: str

    # Individual dimension scores
    name_score: float = 0.0
    geo_score: float = 0.0
    brand_score: float = 0.0
    address_score: float = 0.0
    source_reliability_score: float = 0.0

    # Computed
    composite_score: float = 0.0
    distance_meters: Optional[float] = None   # Raw distance used for geo_score

    @field_validator(
        "name_score", "geo_score", "brand_score", "address_score",
        "source_reliability_score", "composite_score",
        mode="before"
    )
    @classmethod
    def clamp_score(cls, v: Any) -> float:
        try:
            return max(0.0, min(1.0, float(v)))
        except (TypeError, ValueError):
            return 0.0

    def to_storage_dict(self) -> dict[str, Any]:
        return {
            "candidate_id":           self.candidate_id,
            "name_score":             round(self.name_score, 4),
            "geo_score":              round(self.geo_score, 4),
            "brand_score":            round(self.brand_score, 4),
            "address_score":          round(self.address_score, 4),
            "source_reliability_score": round(self.source_reliability_score, 4),
            "composite_score":        round(self.composite_score, 4),
            "distance_meters":        self.distance_meters,
        }


# ═══════════════════════════════════════════════════════════
# MATCH DECISION — the outcome of resolving a scored candidate
# ═══════════════════════════════════════════════════════════

class MatchDecision(BaseModel):
    """
    The result of applying resolution thresholds to a MatchScores object.
    Stored in match_decisions table.
    """
    decision_id: str                          # UUID v4
    candidate_id: str
    master_id: Optional[str] = None           # Set when decision = auto_match or manual_match
    decision: DecisionType
    decided_by: str = "system"                # 'system' or user identifier
    decided_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    notes: Optional[str] = None
    composite_score: float = 0.0              # Copied from MatchScores for convenience

    @property
    def is_match(self) -> bool:
        return self.decision in (DecisionType.AUTO_MATCH, DecisionType.MANUAL_MATCH)


# ═══════════════════════════════════════════════════════════
# MATCH EXPLANATION — human-readable explanation for review
# ═══════════════════════════════════════════════════════════

class MatchExplanation(BaseModel):
    """
    Human-readable explanation of a match decision.
    Stored as JSON in candidate_matches.explanation column.
    """
    candidate_id: str

    # Source info
    source_a_type: str
    source_a_id: str
    source_a_name: Optional[str] = None
    source_a_address: Optional[str] = None
    source_a_lat: Optional[float] = None
    source_a_lng: Optional[float] = None

    source_b_type: str
    source_b_id: str
    source_b_name: Optional[str] = None
    source_b_address: Optional[str] = None
    source_b_lat: Optional[float] = None
    source_b_lng: Optional[float] = None

    # Scores (mirrors MatchScores)
    name_score: float
    geo_score: float
    brand_score: float
    address_score: float
    source_reliability_score: float
    composite_score: float
    distance_meters: Optional[float] = None

    # Weights used
    weights: dict[str, float] = Field(default_factory=lambda: {
        "name": 0.25, "geo": 0.35, "brand": 0.20, "address": 0.15, "source_rel": 0.05
    })

    # Human-readable dimension explanations
    name_explanation: Optional[str] = None
    geo_explanation: Optional[str] = None
    brand_explanation: Optional[str] = None
    address_explanation: Optional[str] = None

    # Decision
    decision: str
    decision_reason: str

    model_config = {
        "json_schema_extra": {
            "example": {
                "candidate_id": "cand-abc123",
                "source_a_type": "cre",
                "source_a_id": "MX007",
                "source_a_name": "PEMEX CONDESA CENTRAL",
                "source_b_type": "osm",
                "source_b_id": "node/987654321",
                "source_b_name": "Gasolinera Condesa",
                "composite_score": 0.827,
                "distance_meters": 38.4,
                "decision": "review_queue",
                "decision_reason": "composite_score 0.827 is in review range [0.65, 0.85)",
            }
        }
    }


# ═══════════════════════════════════════════════════════════
# REVIEW QUEUE ITEM — entry in the review_queue table
# ═══════════════════════════════════════════════════════════

class ReviewQueueItem(BaseModel):
    """
    An item in the human review queue. Contains all fields needed for a reviewer
    to make a match/no-match decision without querying other tables.
    """
    queue_id: str                             # UUID v4
    candidate_id: str
    composite_score: float
    priority: int = 5                         # 1=highest, 10=lowest

    # Flattened source A fields
    source_a_type: str
    source_a_id: str
    source_a_name: Optional[str] = None
    source_a_address: Optional[str] = None
    source_a_municipality: Optional[str] = None
    source_a_state: Optional[str] = None
    source_a_lat: Optional[float] = None
    source_a_lng: Optional[float] = None

    # Flattened source B fields
    source_b_type: str
    source_b_id: str
    source_b_name: Optional[str] = None
    source_b_address: Optional[str] = None
    source_b_municipality: Optional[str] = None
    source_b_state: Optional[str] = None
    source_b_lat: Optional[float] = None
    source_b_lng: Optional[float] = None

    # Score breakdown
    distance_meters: Optional[float] = None
    name_score: float = 0.0
    geo_score: float = 0.0
    brand_score: float = 0.0
    address_score: float = 0.0

    # Review metadata
    decision_recommendation: str = "review"  # auto_match | review | reject
    review_reason: str = ""
    status: str = "pending"                   # pending | resolved | skipped
    assigned_to: Optional[str] = None
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    resolved_at: Optional[str] = None

    def to_csv_row(self) -> dict[str, Any]:
        """Flat dict suitable for CSV export."""
        return {
            "queue_id":               self.queue_id,
            "candidate_id":           self.candidate_id,
            "composite_score":        round(self.composite_score, 4),
            "priority":               self.priority,
            "source_a_type":          self.source_a_type,
            "source_a_id":            self.source_a_id,
            "source_a_name":          self.source_a_name,
            "source_a_address":       self.source_a_address,
            "source_a_lat":           self.source_a_lat,
            "source_a_lng":           self.source_a_lng,
            "source_b_type":          self.source_b_type,
            "source_b_id":            self.source_b_id,
            "source_b_name":          self.source_b_name,
            "source_b_address":       self.source_b_address,
            "source_b_lat":           self.source_b_lat,
            "source_b_lng":           self.source_b_lng,
            "distance_meters":        self.distance_meters,
            "name_score":             round(self.name_score, 4),
            "geo_score":              round(self.geo_score, 4),
            "brand_score":            round(self.brand_score, 4),
            "address_score":          round(self.address_score, 4),
            "decision_recommendation": self.decision_recommendation,
            "review_reason":          self.review_reason,
            "status":                 self.status,
            "assigned_to":            self.assigned_to,
        }


# ═══════════════════════════════════════════════════════════
# QA ISSUE — result of a QA check
# ═══════════════════════════════════════════════════════════

class QAIssue(BaseModel):
    """
    A single issue found by a QA check.
    """
    qa_rule: str                              # e.g. "QA-01"
    qa_description: str                       # e.g. "Duplicate PL numbers"
    severity: QASeverity = QASeverity.MEDIUM
    master_id: Optional[str] = None           # Affected master record ID
    detail: str = ""                          # Human-readable explanation of the issue
    extra: dict[str, Any] = Field(default_factory=dict)  # Additional context
    detected_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
